network_selector/flannel/pod_network_cidr: 10.200.0.0/16
network_selector/flannel/service_cluster_cidr: 10.100.200.0/24
plan1_selector/active/allow_privileged_containers: false
plan1_selector/active/description: 'Example: This plan will configure a lightweight
  kubernetes cluster. Not recommended for production workloads.'
plan1_selector/active/disable_deny_escalating_exec: false
plan1_selector/active/master_instances: 1
plan1_selector/active/max_worker_instances: 50
plan1_selector/active/name: small
plan1_selector/active/worker_instances: 3
uaa_oidc: false
uaa_pks_cli_access_token_lifetime: 600
uaa_pks_cli_refresh_token_lifetime: 21600
worker_max_in_flight: 1
