product-name: pivotal-container-service
network-properties:
  network:
    name: ((network_name))
  service_network:
    name: ((service_network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: ((pivotal-container-service/pks_tls/certificate))
      private_key_pem: ((pivotal-container-service/pks_tls/privatekey))
  .properties.network_selector:
    value: flannel
  .properties.network_selector.flannel.pod_network_cidr:
    value: ((network_selector/flannel/pod_network_cidr))
  .properties.network_selector.flannel.service_cluster_cidr:
    value: ((network_selector/flannel/service_cluster_cidr))
  .properties.pks-vrli:
    value: disabled
  .properties.pks_api_hostname:
    value: ((pks_api_hostname))
  .properties.plan1_selector:
    value: Plan Active
  .properties.plan1_selector.active.description:
    value: ((plan1_selector/active/description))
  .properties.plan1_selector.active.master_az_placement:
    value: ((plan1_selector/active/master_az_placement))
  .properties.plan1_selector.active.master_instances:
    value: ((plan1_selector/active/master_instances))
  .properties.plan1_selector.active.max_worker_instances:
    value: ((plan1_selector/active/max_worker_instances))
  .properties.plan1_selector.active.name:
    value: ((plan1_selector/active/name))
  .properties.plan1_selector.active.worker_az_placement:
    value: ((plan1_selector/active/worker_az_placement))
  .properties.plan1_selector.active.worker_instances:
    value: ((plan1_selector/active/worker_instances))
  .properties.proxy_selector:
    value: Disabled
  .properties.sink_resources_selector:
    value: enabled
  .properties.syslog_selector:
    value: disabled
  .properties.uaa:
    value: internal
  .properties.uaa_oidc:
    value: ((uaa_oidc))
  .properties.uaa_pks_cli_access_token_lifetime:
    value: ((uaa_pks_cli_access_token_lifetime))
  .properties.uaa_pks_cli_refresh_token_lifetime:
    value: ((uaa_pks_cli_refresh_token_lifetime))
  .properties.wavefront:
    value: disabled
  .properties.worker_max_in_flight:
    value: ((worker_max_in_flight))
resource-config:
  pivotal-container-service:
    instance_type:
      id: ((pivotal-container-service_instance_type))
    persistent_disk:
      size_mb: ((pivotal-container-service_persistent_disk_size))
errand-config:
  delete-all-clusters:
    post-deploy-state: ((delete-all-clusters_post_deploy_state))
    pre-delete-state: ((delete-all-clusters_pre_delete_state))
  pks-nsx-t-precheck:
    post-deploy-state: ((pks-nsx-t-precheck_post_deploy_state))
    pre-delete-state: ((pks-nsx-t-precheck_pre_delete_state))
  smoke-tests:
    post-deploy-state: ((smoke-tests_post_deploy_state))
    pre-delete-state: ((smoke-tests_pre_delete_state))
  upgrade-all-service-instances:
    post-deploy-state: ((upgrade-all-service-instances_post_deploy_state))
    pre-delete-state: ((upgrade-all-service-instances_pre_delete_state))
  wavefront-alert-creation:
    post-deploy-state: ((wavefront-alert-creation_post_deploy_state))
    pre-delete-state: ((wavefront-alert-creation_pre_delete_state))
  wavefront-alert-deletion:
    post-deploy-state: ((wavefront-alert-deletion_post_deploy_state))
    pre-delete-state: ((wavefront-alert-deletion_pre_delete_state))
